//! # Trident Generated Types
//!
//! This file is automatically generated by Trident.
//! **DO NOT EDIT THIS FILE MANUALLY**

#![allow(dead_code)]
#![allow(unused_imports)]

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use trident_fuzz::fuzzing::*;

// ============================================================================
// PROGRAM MODULES
// ============================================================================

// ----------------------------------------------------------------------------
// Program: thawgate_gate
// ----------------------------------------------------------------------------
pub mod thawgate_gate {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for thawgate_gate
    pub fn program_id() -> Pubkey {
        pubkey!("THAW2daLXyUtCLtTsJWDTKZctiAGmGX4wT1kqKXugUZ")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: CanFreezePermissionless
    // ....................................................................

    /// Main instruction struct for CanFreezePermissionless
    pub struct CanFreezePermissionlessInstruction {
        pub accounts: CanFreezePermissionlessInstructionAccountMetas,
        pub data: CanFreezePermissionlessInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CanFreezePermissionless instruction
    #[derive(Debug, Clone, Default)]
    pub struct CanFreezePermissionlessInstructionAccountMetas {
        pub caller: AccountMeta,

        pub token_account: AccountMeta,

        pub mint: AccountMeta,

        pub owner: AccountMeta,

        pub flag_account: AccountMeta,
    }

    /// Account pubkeys for CanFreezePermissionless instruction
    #[derive(Debug, Clone)]
    pub struct CanFreezePermissionlessInstructionAccounts {
        pub caller: Pubkey,

        pub token_account: Pubkey,

        pub mint: Pubkey,

        pub owner: Pubkey,

        pub flag_account: Pubkey,
    }

    impl CanFreezePermissionlessInstructionAccounts {
        pub fn new(
            caller: Pubkey,

            token_account: Pubkey,

            mint: Pubkey,

            owner: Pubkey,

            flag_account: Pubkey,
        ) -> Self {
            Self {
                caller,

                token_account,

                mint,

                owner,

                flag_account,
            }
        }
    }

    /// Instruction data for CanFreezePermissionless
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CanFreezePermissionlessInstructionData {}

    impl CanFreezePermissionlessInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for CanFreezePermissionlessInstruction
    impl CanFreezePermissionlessInstruction {
        fn discriminator() -> [u8; 8] {
            [214u8, 141u8, 109u8, 75u8, 248u8, 1u8, 45u8, 29u8]
        }

        pub fn data(data: CanFreezePermissionlessInstructionData) -> Self {
            Self {
                accounts: CanFreezePermissionlessInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CanFreezePermissionlessInstructionAccounts) -> Self {
            self.accounts.caller = AccountMeta::new_readonly(accounts.caller, false);

            self.accounts.token_account = AccountMeta::new_readonly(accounts.token_account, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.owner = AccountMeta::new_readonly(accounts.owner, false);

            self.accounts.flag_account = AccountMeta::new_readonly(accounts.flag_account, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.caller.clone());

            metas.push(self.accounts.token_account.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.owner.clone());

            metas.push(self.accounts.flag_account.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: CanThawPermissionless
    // ....................................................................

    /// Main instruction struct for CanThawPermissionless
    pub struct CanThawPermissionlessInstruction {
        pub accounts: CanThawPermissionlessInstructionAccountMetas,
        pub data: CanThawPermissionlessInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CanThawPermissionless instruction
    #[derive(Debug, Clone, Default)]
    pub struct CanThawPermissionlessInstructionAccountMetas {
        pub caller: AccountMeta,

        pub token_account: AccountMeta,

        pub mint: AccountMeta,

        pub owner: AccountMeta,

        pub flag_account: AccountMeta,
    }

    /// Account pubkeys for CanThawPermissionless instruction
    #[derive(Debug, Clone)]
    pub struct CanThawPermissionlessInstructionAccounts {
        pub caller: Pubkey,

        pub token_account: Pubkey,

        pub mint: Pubkey,

        pub owner: Pubkey,

        pub flag_account: Pubkey,
    }

    impl CanThawPermissionlessInstructionAccounts {
        pub fn new(
            caller: Pubkey,

            token_account: Pubkey,

            mint: Pubkey,

            owner: Pubkey,

            flag_account: Pubkey,
        ) -> Self {
            Self {
                caller,

                token_account,

                mint,

                owner,

                flag_account,
            }
        }
    }

    /// Instruction data for CanThawPermissionless
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CanThawPermissionlessInstructionData {}

    impl CanThawPermissionlessInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for CanThawPermissionlessInstruction
    impl CanThawPermissionlessInstruction {
        fn discriminator() -> [u8; 8] {
            [8u8, 175u8, 169u8, 129u8, 137u8, 74u8, 61u8, 241u8]
        }

        pub fn data(data: CanThawPermissionlessInstructionData) -> Self {
            Self {
                accounts: CanThawPermissionlessInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CanThawPermissionlessInstructionAccounts) -> Self {
            self.accounts.caller = AccountMeta::new_readonly(accounts.caller, false);

            self.accounts.token_account = AccountMeta::new_readonly(accounts.token_account, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.owner = AccountMeta::new_readonly(accounts.owner, false);

            self.accounts.flag_account = AccountMeta::new_readonly(accounts.flag_account, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.caller.clone());

            metas.push(self.accounts.token_account.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.owner.clone());

            metas.push(self.accounts.flag_account.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: InitPolicy
    // ....................................................................

    /// Main instruction struct for InitPolicy
    pub struct InitPolicyInstruction {
        pub accounts: InitPolicyInstructionAccountMetas,
        pub data: InitPolicyInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for InitPolicy instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitPolicyInstructionAccountMetas {
        pub freeze_authority: AccountMeta,

        pub payer: AccountMeta,

        pub policy: AccountMeta,

        pub mint: AccountMeta,

        pub mint_config: AccountMeta,

        pub thaw_extra_metas: AccountMeta,

        pub freeze_extra_metas: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for InitPolicy instruction
    #[derive(Debug, Clone)]
    pub struct InitPolicyInstructionAccounts {
        pub freeze_authority: Pubkey,

        pub payer: Pubkey,

        pub policy: Pubkey,

        pub mint: Pubkey,

        pub mint_config: Pubkey,

        pub thaw_extra_metas: Pubkey,

        pub freeze_extra_metas: Pubkey,
    }

    impl InitPolicyInstructionAccounts {
        pub fn new(
            freeze_authority: Pubkey,

            payer: Pubkey,

            policy: Pubkey,

            mint: Pubkey,

            mint_config: Pubkey,

            thaw_extra_metas: Pubkey,

            freeze_extra_metas: Pubkey,
        ) -> Self {
            Self {
                freeze_authority,

                payer,

                policy,

                mint,

                mint_config,

                thaw_extra_metas,

                freeze_extra_metas,
            }
        }
    }

    /// Instruction data for InitPolicy
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitPolicyInstructionData {
        pub args: PolicyArgs,
    }

    impl InitPolicyInstructionData {
        pub fn new(args: PolicyArgs) -> Self {
            Self { args }
        }
    }

    /// Implementation for InitPolicyInstruction
    impl InitPolicyInstruction {
        fn discriminator() -> [u8; 8] {
            [45u8, 234u8, 110u8, 100u8, 209u8, 146u8, 191u8, 86u8]
        }

        pub fn data(data: InitPolicyInstructionData) -> Self {
            Self {
                accounts: InitPolicyInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: InitPolicyInstructionAccounts) -> Self {
            self.accounts.freeze_authority =
                AccountMeta::new_readonly(accounts.freeze_authority, true);

            self.accounts.payer = AccountMeta::new(accounts.payer, true);

            self.accounts.policy = AccountMeta::new(accounts.policy, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.mint_config = AccountMeta::new_readonly(accounts.mint_config, false);

            self.accounts.thaw_extra_metas = AccountMeta::new(accounts.thaw_extra_metas, false);

            self.accounts.freeze_extra_metas = AccountMeta::new(accounts.freeze_extra_metas, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.freeze_authority.clone());

            metas.push(self.accounts.payer.clone());

            metas.push(self.accounts.policy.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.mint_config.clone());

            metas.push(self.accounts.thaw_extra_metas.clone());

            metas.push(self.accounts.freeze_extra_metas.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: SetupExtraMetas
    // ....................................................................

    /// Main instruction struct for SetupExtraMetas
    pub struct SetupExtraMetasInstruction {
        pub accounts: SetupExtraMetasInstructionAccountMetas,
        pub data: SetupExtraMetasInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for SetupExtraMetas instruction
    #[derive(Debug, Clone, Default)]
    pub struct SetupExtraMetasInstructionAccountMetas {
        pub authority: AccountMeta,

        pub payer: AccountMeta,

        pub policy: AccountMeta,

        pub mint: AccountMeta,

        pub thaw_extra_metas: AccountMeta,

        pub freeze_extra_metas: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for SetupExtraMetas instruction
    #[derive(Debug, Clone)]
    pub struct SetupExtraMetasInstructionAccounts {
        pub authority: Pubkey,

        pub payer: Pubkey,

        pub policy: Pubkey,

        pub mint: Pubkey,

        pub thaw_extra_metas: Pubkey,

        pub freeze_extra_metas: Pubkey,
    }

    impl SetupExtraMetasInstructionAccounts {
        pub fn new(
            authority: Pubkey,

            payer: Pubkey,

            policy: Pubkey,

            mint: Pubkey,

            thaw_extra_metas: Pubkey,

            freeze_extra_metas: Pubkey,
        ) -> Self {
            Self {
                authority,

                payer,

                policy,

                mint,

                thaw_extra_metas,

                freeze_extra_metas,
            }
        }
    }

    /// Instruction data for SetupExtraMetas
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SetupExtraMetasInstructionData {}

    impl SetupExtraMetasInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for SetupExtraMetasInstruction
    impl SetupExtraMetasInstruction {
        fn discriminator() -> [u8; 8] {
            [160u8, 172u8, 133u8, 35u8, 114u8, 239u8, 51u8, 158u8]
        }

        pub fn data(data: SetupExtraMetasInstructionData) -> Self {
            Self {
                accounts: SetupExtraMetasInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SetupExtraMetasInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self.accounts.payer = AccountMeta::new(accounts.payer, true);

            self.accounts.policy = AccountMeta::new(accounts.policy, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.thaw_extra_metas = AccountMeta::new(accounts.thaw_extra_metas, false);

            self.accounts.freeze_extra_metas = AccountMeta::new(accounts.freeze_extra_metas, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.payer.clone());

            metas.push(self.accounts.policy.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.thaw_extra_metas.clone());

            metas.push(self.accounts.freeze_extra_metas.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: UpdatePolicy
    // ....................................................................

    /// Main instruction struct for UpdatePolicy
    pub struct UpdatePolicyInstruction {
        pub accounts: UpdatePolicyInstructionAccountMetas,
        pub data: UpdatePolicyInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for UpdatePolicy instruction
    #[derive(Debug, Clone, Default)]
    pub struct UpdatePolicyInstructionAccountMetas {
        pub authority: AccountMeta,

        pub payer: AccountMeta,

        pub policy: AccountMeta,

        pub mint: AccountMeta,

        pub thaw_extra_metas: AccountMeta,

        pub freeze_extra_metas: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for UpdatePolicy instruction
    #[derive(Debug, Clone)]
    pub struct UpdatePolicyInstructionAccounts {
        pub authority: Pubkey,

        pub payer: Pubkey,

        pub policy: Pubkey,

        pub mint: Pubkey,

        pub thaw_extra_metas: Pubkey,

        pub freeze_extra_metas: Pubkey,
    }

    impl UpdatePolicyInstructionAccounts {
        pub fn new(
            authority: Pubkey,

            payer: Pubkey,

            policy: Pubkey,

            mint: Pubkey,

            thaw_extra_metas: Pubkey,

            freeze_extra_metas: Pubkey,
        ) -> Self {
            Self {
                authority,

                payer,

                policy,

                mint,

                thaw_extra_metas,

                freeze_extra_metas,
            }
        }
    }

    /// Instruction data for UpdatePolicy
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct UpdatePolicyInstructionData {
        pub args: PolicyArgs,
    }

    impl UpdatePolicyInstructionData {
        pub fn new(args: PolicyArgs) -> Self {
            Self { args }
        }
    }

    /// Implementation for UpdatePolicyInstruction
    impl UpdatePolicyInstruction {
        fn discriminator() -> [u8; 8] {
            [212u8, 245u8, 246u8, 7u8, 163u8, 151u8, 18u8, 57u8]
        }

        pub fn data(data: UpdatePolicyInstructionData) -> Self {
            Self {
                accounts: UpdatePolicyInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: UpdatePolicyInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, true);

            self.accounts.payer = AccountMeta::new(accounts.payer, true);

            self.accounts.policy = AccountMeta::new(accounts.policy, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.thaw_extra_metas = AccountMeta::new(accounts.thaw_extra_metas, false);

            self.accounts.freeze_extra_metas = AccountMeta::new(accounts.freeze_extra_metas, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.payer.clone());

            metas.push(self.accounts.policy.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.thaw_extra_metas.clone());

            metas.push(self.accounts.freeze_extra_metas.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

/// Custom enum: AllowlistMode
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub enum AllowlistMode {
    Off,

    AllowOnly,

    BypassForPdas,
}

/// Custom struct: GatePolicy
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct GatePolicy {
    pub version: u8,

    pub bump: u8,

    pub mint: Pubkey,

    pub authority: Pubkey,

    pub issuer_program: Pubkey,

    pub check_blacklist: bool,

    pub allowlist_mode: AllowlistMode,

    pub require_sas: bool,

    pub sas_credential: Pubkey,

    pub sas_schema: Pubkey,

    pub min_kyc_level: u8,

    pub reserved: [u8; 64],
}

impl GatePolicy {
    pub fn new(
        version: u8,

        bump: u8,

        mint: Pubkey,

        authority: Pubkey,

        issuer_program: Pubkey,

        check_blacklist: bool,

        allowlist_mode: AllowlistMode,

        require_sas: bool,

        sas_credential: Pubkey,

        sas_schema: Pubkey,

        min_kyc_level: u8,

        reserved: [u8; 64],
    ) -> Self {
        Self {
            version,

            bump,

            mint,

            authority,

            issuer_program,

            check_blacklist,

            allowlist_mode,

            require_sas,

            sas_credential,

            sas_schema,

            min_kyc_level,

            reserved,
        }
    }
}

/// Custom struct: PolicyArgs
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct PolicyArgs {
    pub authority: Pubkey,

    pub issuer_program: Pubkey,

    pub check_blacklist: bool,

    pub allowlist_mode: AllowlistMode,

    pub require_sas: bool,

    pub sas_credential: Pubkey,

    pub sas_schema: Pubkey,

    pub min_kyc_level: u8,
}

impl PolicyArgs {
    pub fn new(
        authority: Pubkey,

        issuer_program: Pubkey,

        check_blacklist: bool,

        allowlist_mode: AllowlistMode,

        require_sas: bool,

        sas_credential: Pubkey,

        sas_schema: Pubkey,

        min_kyc_level: u8,
    ) -> Self {
        Self {
            authority,

            issuer_program,

            check_blacklist,

            allowlist_mode,

            require_sas,

            sas_credential,

            sas_schema,

            min_kyc_level,
        }
    }
}

// ============================================================================
// END OF GENERATED FILE
// ============================================================================
