[workspace]
members = [
    "programs/sss-token",
    "programs/transfer-hook",
    "programs/oracle-module",
    "programs/thawgate-gate",
]
resolver = "2"

[workspace.dependencies]
anchor-lang = { version = "0.32.2", features = ["init-if-needed"] }
anchor-spl = { version = "0.32.2", features = ["token_2022", "associated_token"] }
spl-token-2022 = { version = "8", features = ["no-entrypoint"] }
spl-transfer-hook-interface = "0.10"
spl-tlv-account-resolution = "0.10"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1

[workspace.lints.rust]
unused_comparisons = "allow"
unexpected_cfgs = "allow"

[workspace.lints.clippy]
absurd_extreme_comparisons = "allow"
assertions_on_constants = "allow"
bool_assert_comparison = "allow"
