/**
 * @module client
 * @description SolanaStablecoin — the main SDK entrypoint class.
 *
 * Provides a high-level, ergonomic API for interacting with SSS stablecoins.
 * Wraps all base operations, role management, and compliance modules.
 *
 * @example
 * ```ts
 * import { SolanaStablecoin, sss1Preset } from "@thawgate/sdk";
 *
 * const client = SolanaStablecoin.fromConfig({
 *   rpcUrl: "https://api.devnet.solana.com",
 *   programId: new PublicKey("..."),
 * });
 *
 * // Initialize a new SSS-1 stablecoin
 * const { instructions, mint } = await client.initialize(
 *   authority.publicKey,
 *   sss1Preset("USD Stablecoin", "USDS", "https://meta.example.com", 6),
 * );
 * ```
 */

import {
    PublicKey,
    Commitment,
    ComputeBudgetProgram,
    Connection,
    Keypair,
    Signer,
    SystemProgram,
    SYSVAR_CLOCK_PUBKEY,
    TransactionInstruction,
} from "@solana/web3.js";
import { Program, AnchorProvider } from "@coral-xyz/anchor";
import { TOKEN_2022_PROGRAM_ID } from "@solana/spl-token";
import BN from "bn.js";
import {
    findConfigPda,
    findPauseStatePda,
    findRolePda,
    findQuotaPda,
} from "./pda";
import { GateClient, PolicyInput, toGatePolicyConfig } from "./gate/client";
import { findFreezeExtraMetasPda, findMintConfigPda, findThawExtraMetasPda } from "./gate/tokenAcl";
import { sssAclPreset } from "./presets/sssAcl";
import { keypairWallet } from "./wallet";
import * as tokenOps from "./base/token";
import * as roleOps from "./base/roles";
import { ComplianceModule } from "./modules/compliance";
import { PrivacyModule } from "./modules/privacy";
import { ReservesModule } from "./modules/reserves";
import IDL from "./idl.json";
import { SSS_TOKEN_PROGRAM_ID, TOKEN_ACL_PROGRAM_ID, TRANSFER_HOOK_PROGRAM_ID } from "./programs";
import type {
    SSSClientConfig,
    InitializeArgs,
    StablecoinConfig,
    RoleRecord,
    MinterQuota,
    PauseState,
} from "./types";
import { RoleType, QuotaPeriod } from "./types";
import { ConfigError, AccountNotFoundError, parseError } from "./errors";

// Placeholder program ID patterns — used for validation only.
// These must NOT be shipped as defaults; callers must configure real IDs.
const PLACEHOLDER_PATTERNS = [
    "SSSToken11111111111111111111111111111111111",
    "Hook111111111111111111111111111111111111111",
    "11111111111111111111111111111111",
];

/**
 * Validates that a program ID is not a known placeholder.
 * Throws ConfigError if the ID matches a placeholder pattern.
 */
function validateProgramId(id: PublicKey | undefined, name: string): void {
    if (!id) {
        throw new ConfigError(
            `${name} is not configured. Provide it in the SDK config.`,
        );
    }
    const idStr = id.toBase58();
    if (PLACEHOLDER_PATTERNS.includes(idStr)) {
        throw new ConfigError(
            `${name} is set to a placeholder value (${idStr}). ` +
            `Configure the real deployed program ID.`,
        );
    }
}

type Amount = BN | bigint | number | string;
const toBN = (a: Amount) => (BN.isBN(a) ? (a as BN) : new BN(a.toString()));

/** Options for {@link SolanaStablecoin.createStablecoin}. Amounts are base units (10^decimals per token). */
export interface CreateStablecoinOptions {
    name: string;
    symbol: string;
    uri?: string;
    /** Default 6. */
    decimals?: number;
    /** The ThawGate policy. `issuerProgram` and `authority` are set by sss-token (itself, and the issuer's wallet). */
    policy: PolicyInput;
    reserves: {
        /** Reserves to post now, in base units: the supply can't exceed it. */
        amount: Amount;
        /** Link to the reserve report (at most 200 bytes). */
        reportUri: string;
        /** How old a post may be before minting stops. Default 86,400 s (1 day). */
        maxStalenessSeconds?: number;
        /** Who posts reserves. Default: the wallet, which then posts `amount` now; another attestor posts later. */
        attestor?: PublicKey;
    };
    /** The Minter role and quota; default the wallet with quota = reserves, lifetime. `false` grants none. */
    minter?: { address?: PublicKey; quota?: Amount; period?: QuotaPeriod } | false;
    /** Create the mint with the sss-token allowlist on. Default: on when the policy's allowlistMode isn't "off". */
    enableAllowlist?: boolean;
    /** The mint's keypair (vanity addresses); generated by default. */
    mintKeypair?: Keypair;
}

export interface CreatedStablecoin {
    mint: PublicKey;
    signatures: { initialize: string; enableTokenAcl: string; setup: string };
}

/**
 * SolanaStablecoin — main SDK class.
 *
 * Acts as a facade over all SSS operations. Provides both
 * instruction builders (for composability) and convenience
 * methods for common workflows.
 */
export class SolanaStablecoin {
    /** The Anchor program instance. */
    public readonly program: Program;
    /** The Solana connection. */
    public readonly connection: Connection;
    /** The SSS-Token program ID. */
    public readonly programId: PublicKey;
    /** The transfer hook program ID. */
    public readonly hookProgramId: PublicKey;
    /** The signing wallet, if the client was created with one. */
    public readonly wallet?: AnchorProvider["wallet"];
    /** ThawGate policies and holder flows (unlock, explain, freeze-if-invalid) for this client's mints. */
    public readonly gate: GateClient;

    private constructor(
        program: Program,
        connection: Connection,
        programId: PublicKey,
        hookProgramId: PublicKey,
        wallet: AnchorProvider["wallet"] | undefined,
        gateProgramId: PublicKey | undefined,
        commitment: Commitment,
    ) {
        this.program = program;
        this.connection = connection;
        this.programId = programId;
        this.hookProgramId = hookProgramId;
        this.wallet = wallet;
        this.gate = new GateClient(connection, wallet, { gateProgramId, commitment });
    }

    /**
     * Creates a new SolanaStablecoin instance.
     *
     * Primary static factory method as required by the SSS PRD specification.
     * Accepts a Connection object directly (PRD pattern) or creates one from config.rpcUrl.
     *
     * @param connectionOrConfig - A Solana Connection, or SSSClientConfig
     * @param configOrWallet - SSSClientConfig if first arg is Connection, or wallet
     * @param wallet - Anchor wallet (optional for read-only)
     * @returns A new SolanaStablecoin instance
     */
    static async create(
        connectionOrConfig: Connection | SSSClientConfig,
        configOrWallet?: SSSClientConfig | AnchorProvider["wallet"],
        wallet?: AnchorProvider["wallet"],
    ): Promise<SolanaStablecoin> {
        let config: SSSClientConfig;
        let resolvedWallet: AnchorProvider["wallet"] | undefined;

        if (connectionOrConfig instanceof Connection) {
            // PRD pattern: create(connection, config)
            config = (configOrWallet as SSSClientConfig) ?? { rpcUrl: "" };
            // Override rpcUrl since we already have a connection
            config = { ...config, rpcUrl: config.rpcUrl || "provided-via-connection" };
            resolvedWallet = wallet;
        } else {
            // Legacy pattern: create(config, wallet?)
            config = connectionOrConfig;
            resolvedWallet = configOrWallet as AnchorProvider["wallet"] | undefined;
        }

        return SolanaStablecoin.fromConfig(config, resolvedWallet);
    }

    /**
     * Creates a new SolanaStablecoin instance from configuration.
     *
     * Alias for {@link SolanaStablecoin.create} — kept for backward compatibility.
     *
     * @param config - Client configuration
     * @param walletOrKeypair - Anchor wallet or a Keypair (optional for read-only)
     * @returns A new SolanaStablecoin instance
     */
    static fromConfig(
        config: SSSClientConfig,
        walletOrKeypair?: AnchorProvider["wallet"] | Keypair,
    ): SolanaStablecoin {
        if (!config.rpcUrl) {
            throw new ConfigError("rpcUrl is required");
        }
        const wallet = walletOrKeypair instanceof Keypair ? keypairWallet(walletOrKeypair) : walletOrKeypair;
        const commitment = config.commitment ?? "confirmed";

        const connection = new Connection(
            config.rpcUrl,
            config.commitment ?? "confirmed",
        );

        // Default: the devnet deployments (localnet uses the same IDs).
        const programId = config.programId ?? SSS_TOKEN_PROGRAM_ID;
        const hookProgramId = config.hookProgramId ?? TRANSFER_HOOK_PROGRAM_ID;

        // Validate program IDs — reject placeholders and missing IDs
        validateProgramId(programId, "SSS Token program ID (programId)");
        validateProgramId(hookProgramId, "Transfer Hook program ID (hookProgramId)");

        // After validation, we know these are defined and valid
        const validProgramId = programId!;
        const validHookProgramId = hookProgramId!;

        // Create a read-only provider if no wallet is provided
        const provider = wallet
            ? new AnchorProvider(connection, wallet, {
                commitment,
                // The blockhash and preflight at the same level as confirmation ("Blockhash not found" otherwise).
                preflightCommitment: commitment,
                skipPreflight: config.skipPreflight ?? false,
            })
            : ({
                connection,
                publicKey: PublicKey.default,
            } as unknown as AnchorProvider);

        // Create program with the actual IDL bundled with the SDK.
        const ProgramCtor: new (...args: unknown[]) => Program = Program as unknown as new (...args: unknown[]) => Program;
        const program = new ProgramCtor(
            { ...IDL, address: validProgramId.toBase58() } as any,
            provider,
        );

        return new SolanaStablecoin(program, connection, validProgramId, validHookProgramId, wallet, config.gateProgramId, commitment);
    }

    // ============================================================================
    // Issuer: SSS-ACL stablecoins gated by ThawGate
    // ============================================================================

    private requireWallet(what: string): AnchorProvider["wallet"] {
        if (!this.wallet) throw new ConfigError(`${what} needs a wallet: SolanaStablecoin.fromConfig(config, wallet)`);
        return this.wallet;
    }

    /**
     * sss-token `enable_token_acl`: creates the mint's Token ACL config (gate = ThawGate, permissionless thaw and
     * freeze on) and its ThawGate policy, with the issuer's master authority as policy authority and sss-token as
     * the blacklist/allowlist program. MasterAuthority only.
     */
    async enableTokenAcl(mint: PublicKey, policy: PolicyInput, authority?: PublicKey): Promise<TransactionInstruction[]> {
        const signer = authority ?? this.requireWallet("enableTokenAcl").publicKey;
        const gateProgram = this.gate.gateProgramId;
        try {
            const ix = await this.program.methods
                .enableTokenAcl(toGatePolicyConfig(policy))
                .accountsStrict({
                    authority: signer,
                    config: findConfigPda(mint, this.programId)[0],
                    authorityRole: findRolePda(mint, signer, RoleType.MasterAuthority, this.programId)[0],
                    mint,
                    tokenAclProgram: TOKEN_ACL_PROGRAM_ID,
                    mintConfig: findMintConfigPda(mint),
                    gateProgram,
                    gatePolicy: this.gate.policyAddress(mint),
                    thawExtraMetas: findThawExtraMetasPda(mint, gateProgram),
                    freezeExtraMetas: findFreezeExtraMetasPda(mint, gateProgram),
                    tokenProgram: TOKEN_2022_PROGRAM_ID,
                    systemProgram: SystemProgram.programId,
                })
                .instruction();
            return [ix];
        } catch (error) {
            throw parseError(error);
        }
    }

    /**
     * Creates an SSS-ACL stablecoin gated by ThawGate, ready to mint, in three transactions:
     * 1. `initialize` with the SSS-ACL preset (accounts start frozen);
     * 2. `enable_token_acl` with `policy`;
     * 3. the minter role and quota, the reserve attestor, and (when the wallet is the attestor) a first reserve post.
     *
     * The wallet becomes MasterAuthority and the policy authority. Minting needs reserves: every `mint_tokens`
     * checks `supply + amount <= reserves` and that the post is fresher than `maxStalenessSeconds`.
     */
    async createStablecoin(opts: CreateStablecoinOptions): Promise<CreatedStablecoin> {
        const authority = this.requireWallet("createStablecoin").publicKey;
        const allowlistOn = (opts.policy.allowlistMode ?? "off") !== "off";
        const args = { ...sssAclPreset(opts.name, opts.symbol, opts.uri ?? "", opts.decimals ?? 6), enableAllowlist: opts.enableAllowlist ?? allowlistOn };
        const { instructions, mint, mintKeypair } = await this.initialize(authority, args, opts.mintKeypair);
        const initialize = await this.send(instructions, [mintKeypair]);

        // enable_token_acl makes four CPIs (Token ACL create_config + toggle, the metadata field, the gate's init_policy).
        const enableTokenAcl = await this.send([
            ComputeBudgetProgram.setComputeUnitLimit({ units: 400_000 }),
            ...(await this.enableTokenAcl(mint, opts.policy, authority)),
        ]);

        const amount = toBN(opts.reserves.amount);
        const attestor = opts.reserves.attestor ?? authority;
        const setup: TransactionInstruction[] = [];
        if (opts.minter !== false) {
            const m = opts.minter ?? {};
            setup.push(...(await this.updateMinter(mint, authority, m.address ?? authority, toBN(m.quota ?? amount), m.period ?? QuotaPeriod.Lifetime)));
        }
        const reserves = this.reserves(mint);
        setup.push(...(await reserves.setReserveAttestor(authority, attestor, opts.reserves.maxStalenessSeconds ?? 86_400)));
        if (attestor.equals(authority)) {
            setup.push(...(await reserves.attestReserves(authority, amount, await this.clusterTime(), opts.reserves.reportUri)));
        }
        const setupSig = await this.send(setup);
        return { mint, signatures: { initialize, enableTokenAcl, setup: setupSig } };
    }

    /**
     * The cluster's unix time (Clock sysvar). Reserve posts must use it: `attest_reserves` refuses an `as_of` in the
     * future, and a local clock can run ahead of the cluster.
     */
    async clusterTime(): Promise<number> {
        const clock = await this.connection.getAccountInfo(SYSVAR_CLOCK_PUBKEY);
        if (!clock) throw new Error("Clock sysvar not found");
        return Number(clock.data.readBigInt64LE(32));
    }

    /** Sign with the client's wallet (plus `signers`), send, and confirm. Returns the signature. */
    async send(instructions: TransactionInstruction[], signers: Signer[] = []): Promise<string> {
        this.requireWallet("send");
        return this.gate.send(instructions, signers);
    }

    // ============================================================================
    // Token Operations
    // ============================================================================

    /**
     * Initializes a new stablecoin.
     *
     * @param authority - The authority's public key (becomes MasterAuthority)
     * @param args - Initialization arguments (use sss1Preset or sss2Preset)
     * @param mintKeypair - Optional mint keypair (generated if not provided)
     */
    async initialize(
        authority: PublicKey,
        args: InitializeArgs,
        mintKeypair?: Keypair,
    ): Promise<{
        instructions: TransactionInstruction[];
        mint: PublicKey;
        mintKeypair: Keypair;
    }> {
        return tokenOps.initialize(this.program, authority, args, mintKeypair);
    }

    /**
     * Mints tokens to a recipient.
     */
    async mintTokens(
        mint: PublicKey,
        minter: PublicKey,
        recipient: PublicKey,
        amount: BN,
    ): Promise<TransactionInstruction[]> {
        return tokenOps.mintTokens(this.program, mint, minter, recipient, amount);
    }

    /**
     * Burns tokens from the burner's account.
     */
    async burnTokens(
        mint: PublicKey,
        burner: PublicKey,
        amount: BN,
    ): Promise<TransactionInstruction[]> {
        return tokenOps.burnTokens(this.program, mint, burner, amount);
    }

    /**
     * Freezes a target token account.
     */
    async freezeAccount(
        mint: PublicKey,
        operator: PublicKey,
        targetTokenAccount: PublicKey,
        operatorRole?: RoleType.MasterAuthority | RoleType.Blacklister,
    ): Promise<TransactionInstruction[]> {
        return tokenOps.freezeAccount(
            this.program,
            mint,
            operator,
            targetTokenAccount,
            operatorRole,
        );
    }

    /**
     * Thaws a frozen token account.
     */
    async thawAccount(
        mint: PublicKey,
        operator: PublicKey,
        targetTokenAccount: PublicKey,
        operatorRole?: RoleType.MasterAuthority | RoleType.Blacklister,
    ): Promise<TransactionInstruction[]> {
        return tokenOps.thawAccount(
            this.program,
            mint,
            operator,
            targetTokenAccount,
            operatorRole,
        );
    }

    /**
     * Pauses all token operations.
     */
    async pause(
        mint: PublicKey,
        operator: PublicKey,
        operatorRole?: RoleType.Pauser | RoleType.MasterAuthority,
    ): Promise<TransactionInstruction[]> {
        return tokenOps.pause(this.program, mint, operator, operatorRole);
    }

    /**
     * Resumes all token operations.
     */
    async unpause(
        mint: PublicKey,
        operator: PublicKey,
        operatorRole?: RoleType.Pauser | RoleType.MasterAuthority,
    ): Promise<TransactionInstruction[]> {
        return tokenOps.unpause(this.program, mint, operator, operatorRole);
    }

    // ============================================================================
    // Role Operations
    // ============================================================================

    /**
     * Creates or updates a minter with a quota.
     */
    async updateMinter(
        mint: PublicKey,
        authority: PublicKey,
        minter: PublicKey,
        limit: BN,
        period: QuotaPeriod,
    ): Promise<TransactionInstruction[]> {
        return roleOps.updateMinter(
            this.program,
            mint,
            authority,
            minter,
            limit,
            period,
        );
    }

    /**
     * Creates or updates a role for a given key.
     */
    async updateRoles(
        mint: PublicKey,
        authority: PublicKey,
        holder: PublicKey,
        role: RoleType,
        active: boolean,
    ): Promise<TransactionInstruction[]> {
        return roleOps.updateRoles(
            this.program,
            mint,
            authority,
            holder,
            role,
            active,
        );
    }

    /**
     * Transfers MasterAuthority to a new key.
     */
    async transferAuthority(
        mint: PublicKey,
        authority: PublicKey,
        newAuthority: PublicKey,
    ): Promise<TransactionInstruction[]> {
        return roleOps.transferAuthority(
            this.program,
            mint,
            authority,
            newAuthority,
        );
    }

    // ============================================================================
    // Module Accessors
    // ============================================================================

    /**
     * Returns a ComplianceModule for SSS-2 operations on a specific mint.
     */
    compliance(mint: PublicKey): ComplianceModule {
        return new ComplianceModule(this.program, mint);
    }

    /**
     * Returns a PrivacyModule for SSS-3 operations on a specific mint.
     */
    privacy(mint: PublicKey): PrivacyModule {
        return new PrivacyModule(mint);
    }

    /**
     * Returns a ReservesModule for the reserve attestation that `mint_tokens` checks.
     */
    reserves(mint: PublicKey): ReservesModule {
        return new ReservesModule(this.program, mint);
    }

    // ============================================================================
    // Account Fetchers
    // ============================================================================

    /**
     * Typed account fetch helper.
     * Wraps Anchor's program.account access with proper typing.
     */
    private fetchAccount(accountName: string): { fetch: (pda: PublicKey) => Promise<unknown>; all: (filters?: unknown[]) => Promise<unknown[]> } {
        const accounts = this.program.account as Record<string, { fetch: (pda: PublicKey) => Promise<unknown>; all: (filters?: unknown[]) => Promise<unknown[]> }>;
        return accounts[accountName];
    }

    /**
     * Fetches the StablecoinConfig for a mint.
     */
    async getConfig(mint: PublicKey): Promise<StablecoinConfig> {
        const [configPda] = findConfigPda(mint, this.programId);
        try {
            const account = await this.fetchAccount("stablecoinConfig").fetch(configPda);
            return account as StablecoinConfig;
        } catch (error) {
            throw new AccountNotFoundError("StablecoinConfig", configPda.toBase58());
        }
    }

    /**
     * Fetches the PauseState for a mint.
     */
    async getPauseState(mint: PublicKey): Promise<PauseState> {
        const [pausePda] = findPauseStatePda(mint, this.programId);
        try {
            const account = await this.fetchAccount("pauseState").fetch(pausePda);
            return account as PauseState;
        } catch (error) {
            throw new AccountNotFoundError("PauseState", pausePda.toBase58());
        }
    }

    /**
     * Fetches a role record for a given holder and role.
     */
    async getRoleRecord(
        mint: PublicKey,
        holder: PublicKey,
        role: RoleType,
    ): Promise<RoleRecord | null> {
        const [rolePda] = findRolePda(mint, holder, role, this.programId);
        try {
            const account = await this.fetchAccount("roleRecord").fetch(rolePda);
            return account as RoleRecord;
        } catch {
            return null;
        }
    }

    /**
     * Fetches a minter's quota.
     */
    async getMinterQuota(
        mint: PublicKey,
        minter: PublicKey,
    ): Promise<MinterQuota | null> {
        const [quotaPda] = findQuotaPda(mint, minter, this.programId);
        try {
            const account = await this.fetchAccount("minterQuota").fetch(quotaPda);
            return account as MinterQuota;
        } catch {
            return null;
        }
    }

    /**
     * Checks if a wallet has a specific active role.
     */
    async hasRole(
        mint: PublicKey,
        holder: PublicKey,
        role: RoleType,
    ): Promise<boolean> {
        const record = await this.getRoleRecord(mint, holder, role);
        return record?.active ?? false;
    }

    /**
     * Checks if the token is currently paused.
     */
    async isPaused(mint: PublicKey): Promise<boolean> {
        const state = await this.getPauseState(mint);
        return state.paused;
    }
}
